- Gruntfile.js
- lib/child-main.js
- lib/gateways.js
- lib/gui.js
- lib/main.js
- lib/protocols.js
- lib/redirects.js
- test/test-gateways.js
- test/test-gui.js
it's not quite done, but i'd like some feedback. i had to untangle the gui and configuration concerns a bit to make it work in the child process.
> first stab at putting protocol handlers in all processes

- lib/pin.js
- locale/en-US.properties
- package.json
Also, filtered out any get query strings, which can be tested when you click Download on any ipfs.pics instance.
> Add custom api port

- data/test.html
- lib/child-main.js
- lib/gateways.js
- lib/protocols.js
- lib/rewrite-pages.js
- package.json
- test/test-linkify.js
splitting out the linkification work from the url canonization since this pretty much works while the latter is a hairy mess.
> plaintext linkification

- .travis.yml
- lib/gateways.js
- lib/main.js
- lib/protocols.js
- lib/request-fix.js
- package.json
- test/prefs-util.js
- test/test-canonical-fs-uris.js
- test/test-linkify.js
- test/test-protocols.js
It works with and without e10s for basic resource loading and I also tested it against the case in #3. But it most likely needs some further testing to weed out edge-cases, so i've marked it as default-off and experimental.
Basically, from firefox's view this all runs under CORS policy because we're running the HTTP requests with the principals of the fs:/ document instead of implementing our own channels which then delegate to a privileged HTTP channel
Getting the URLs a tiny bit wrong causes redirects from the gateways which then can then void the CORS permissions under circumstances.
Implementing as a custom channel wrapper around http channels might be more robust wrt. CORS but currently is way too troublesome under e10s until the FF devs improve support (or documentation) there.
> support for fs: URIs without redirecting to http:

- CONTRIBUTING.md
- README.md
- SECURITY.md
- add-on/manifest.json
- add-on/src/lib/common.js
- add-on/src/lib/linkifyDOM.js
- package.json
There were miscellaneous lingering references to ipfs/ipfs-firefox-addon (and even lidel/ipfs-firefox-addon!). This updates them to the new repository name.
This PR does _not_ change all references; I left those that seemed possibly entangled with AMO, with which I lack the expertise necessary to avoid breakage.
> update name and related URLs

- add-on/manifest.json
- add-on/src/lib/common.js
- add-on/src/popup/browser-action.js
We had multiple issues with the way Alarms are implemented in Firefox and there are limitations under minimal interval in Chromium-based browsers.
This PR removes use of `browser.alarms.*` for triggering and signaling API status changes within background script and between background script and Browser Action popup.  
IPFS API polling is now handled by simple Interval, and communication with Browser Action popup uses `browser.runtime.*` APIs. 
This PR fixes #218, #259 and #243.
> Refactoring of Browser Action and API Polling

- README.md
Added a sentence explaining IPFS needs to be installed before ipfs-companion will do anything, as this wasn't mentioned.
> Update README, mention the need to have IPFS installed

- add-on/src/lib/linkifyDOM.js
- package.json
This PR:
- adds CID support introduced by https://github.com/ipfs/is-ipfs/pull/13
- this means both CIDv0 and CIDv1 are supported in redirects and "linkify" experiment 
- fixes linkification of text nodes without whitespace prefix
Closes #275
> Add CID Support

- add-on/manifest.json
- add-on/src/lib/common.js
- add-on/src/lib/linkifyDOM.js
- add-on/src/lib/option-defaults.js
- add-on/src/options/options.html
- package.json
- test/unit/00-init.test.js
- test/unit/01-onBeforeRequest.test.js
This is an implementation of ridiculous idea from https://github.com/ipfs/ipfs-companion/issues/164#issuecomment-328374052
I am really sorry, but its the only way to get `dweb://` working across all browsers  🙄  
----
As usual, I am not sure how to label checkbox responsible for toggling this feature in _Preferences_.
Current label looks like this:
> ![2017-09-17-024645_537x81_scrot](https://user-images.githubusercontent.com/157609/30517083-66f32544-9b53-11e7-84a3-789395c7ac8f.png)
Any ideas how to improve it before I merge this PR?
> feat: Poor Man's Protocol Handlers

- add-on/manifest.json
- add-on/src/lib/common.js
- add-on/src/lib/linkifyDOM.js
- add-on/src/lib/normalizeLinksWithUnhandledProtocols.js
- add-on/src/options/options.html
- add-on/src/options/options.js
This PR implements #286.
Content script detects IPFS-related protocols in `href` and `src` attributes of Elements such as `<a>` or `<img>` and replaces them with URL at the user-specified public HTTP gateway.  
If IPFS API is online, HTTP request will be redirected to custom gateway.
This normalization logic is enabled by "Catch Unhandled IPFS Protocols" experiment.
> Normalize dweb: in href and src

- add-on/manifest.json
- add-on/src/lib/common.js
- add-on/src/lib/linkifyDOM.js
ref https://github.com/ipfs/ipfs-companion/issues/286#issuecomment-335553288
> Dnslink fixes

- README.md
This just adds instructions for installing an "unpacked" extension in Firefox (wisdom gleaned from [this article](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Temporary_Installation_in_Firefox)), and makes it obvious that this is the way you'd also do development.
Can anyone help with these questions?:
1. ~~Is `npm run build` necessary in this context?~~ YES - for copy npm deps into lib
2. I've just read the `CONTRIBUTING.md` and it says use `npm start` to get in installed on firefox - is that still the recommended way?
3. Is it usual for dev instructions be in `CONTRIBUTING.md`? I didn't immediately think to look there...should they be in the `README.md` or at least linked to, from the `README.md`?
> Adds firefox development instructions

- package.json
- yarn.lock
Fixes the issue of private, build machine specific fields from package.json appearing in the bundle, by adding https://github.com/fanatid/browserify-package-json as a global browserify transform 
After this change the diff is clean between a local build via `npx yarn@1.2.1 && npx yarn@1.2.1 build` and a `docker-build` run.
See: https://github.com/ipfs/ipfs-companion/pull/311#issuecomment-345771694
> Remove private fields from bundled package.json

- add-on/src/lib/ipfs-companion.js
- add-on/src/popup/browser-action/store.js
In brave the `runtime.openOptionsPage()` call is failing, so the user can't update their prefs.
See: https://github.com/brave/browser-laptop/issues/7812
This PR adds a fallback to opening the options page as a browser tab if the `runtime.openOptionsPage()` throws.
Also, we add try/catch around calls the following _currently_ unsupported apis
- `contextMenus.create`
- `contextMenus.update`
In the meantime I'll [follow up with brave](https://github.com/brave/browser-laptop/issues/9556#issuecomment-345229249) to see what we need to do to make them available.
WIP on #312
> Fallback to opening options page manually in brave

- add-on/src/popup/browser-action/gateway-status.js
- add-on/src/popup/browser-action/index.html
- add-on/src/popup/browser-action/nav-item.js
- add-on/src/popup/browser-action/page.js
Browser menu rendering in brave is super janky. This PR in-lines width and overflow styles to the body element of the menu page so the browser has a clue as early as possible how wide the menu will be. Brave renders a scroll bar on the menu by default, so we disable that too.
The height of our menu changes, which can also causes some render jank, so it'd be worth considering marking menu items as visually disabled rather then pulling them out of the menu when not available.
Also adds explicit color styles to hopefully fix #329 though I've not been able to test it.
> fix: reduce menu render jank

- README.md
Adds instructions on how to try out the plugin in brave.
See the rendered version at: https://github.com/tableflip/ipfs-companion/blob/cea9db9adf764fbb154186f975df50b6790e1aba/README.md#brave
> Fix #340 - Add instructions for Brave

- package.json
- yarn.lock
Previously `ipfs-postmsg-proxy` faked streaming by buffering into memory and then "streaming" a single chunk. It meant that the streaming interfaces worked, but not properly! This PR updates `ipfs-postmsg-proxy` to 2.1.0 which implements proper streaming over `window.postMessage` - hooray \o/
> Updates ipfs-postmsg-proxy with proper streaming support

- CONTRIBUTING.md
- add-on/src/lib/context-menus.js
- add-on/src/lib/ipfs-companion.js
- package.json
- test/functional/lib/ipfs-companion.test.js
- yarn.lock
This PR:
-  fixes init errors caused by missing APIs on Android (there are no context menus, no browserAction icorn/badge)
- updates `web-ext` to v2.3.1 which supports [hot-deploy to emulator,  over USB  and remote debug](https://www.youtube.com/watch?v=fs-mSrap6a8&feature=youtu.be)
- documents how to develop/debug on Android: [CONTRIBUTING.md#firefox-for-android](https://github.com/ipfs-shipyard/ipfs-companion/blob/c49286a71152e2275ea3959d824882e8103a0b7e/CONTRIBUTING.md#firefox-for-android)
Question:
- Should we move development-related instructions from [CONTRIBUTING.md#development](https://github.com/ipfs-shipyard/ipfs-companion/blob/c49286a71152e2275ea3959d824882e8103a0b7e/CONTRIBUTING.md#development) to a section in README, or it good as-is?
> Fixes and docs related to Firefox for Android

- README.md
At some point `browser.ipfs` got removed from the `package.json` - if that was intentional then the docs need to be updated - this PR addresses that.
> Removes docs about flag for embedded js-ipfs

- add-on/_locales/en/messages.json
- add-on/src/lib/ipfs-proxy/access-control.js
- add-on/src/lib/ipfs-proxy/index.js
- add-on/src/lib/ipfs-proxy/pre-acl.js
- add-on/src/lib/ipfs-proxy/request-access.js
- add-on/src/pages/proxy-access-dialog/index.html
- add-on/src/pages/proxy-access-dialog/page.js
- add-on/src/pages/proxy-access-dialog/store.js
- add-on/src/pages/proxy-acl/page.js
- add-on/src/pages/proxy-acl/store.js
- test/functional/lib/ipfs-proxy/access-control.test.js
- test/functional/lib/ipfs-proxy/pre-acl.test.js
- test/functional/pages/proxy-access-dialog/page.test.js
- test/functional/pages/proxy-acl/page.test.js
- test/functional/pages/proxy-acl/store.test.js
🎥 https://youtu.be/v6wuFRDKVBU
This PR introduces scope based permissions - following a similar implementation as service worker registration scopes.
This means that allowing access to:
https://ipfs.io/ipfs/QmQxeMcbqW9npq5h5kyE2iPECR9jxJF4j5x4bSRQ2phLY4/
will allow access to:
https://ipfs.io/ipfs/QmQxeMcbqW9npq5h5kyE2iPECR9jxJF4j5x4bSRQ2phLY4/path/to/something
...but not:
https://ipfs.io/ipfs/QmWfVY9y3xjsixTgbd9AorQxH7VtMpzfx2HaWtsoUYecaX
or other hashes.
resolves #375
---
Permissions are scoped to the **origin and path** (and sub-paths) of the file from which the permission was requested.
Scoped permissions in `window.ipfs` work similarly to how they work for [service worker registrations](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/register#Examples) except …
> Adds scoped permissions

- add-on/src/lib/ipfs-proxy/pre-acl.js
Simply disable access to them for now until we can scope the paths they operate on. Discussion here: https://github.com/ipfs-shipyard/ipfs-companion/issues/330#issuecomment-367651787
Using [this list](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#mutable-file-system) for the list of functions that we should blacklist.
> Temporarily disables access to MFS functions on window.ipfs

- ci/Jenkinsfile
- ci/update-manifest.sh
- package.json
This PR is a prerequisite for https://github.com/ipfs-shipyard/ipfs-companion/issues/385 and ensures we have good times during QA/testing.
It adds a script that modifies manifest during the build, so that produced artifact is clearly marked as Dev Build and includes git revision it was built from:
```
build
└── ipfs_companion_dev_build_bd3da68_-2.2.0.7523.zip
```
Change is also present in Browser UI (addon listing):
> ![2018-02-22-225506_1647x1421_scrot](https://user-images.githubusercontent.com/157609/36566406-b3938838-1823-11e8-8453-489d0d6b83d2.png)
>  ![2018-02-22-225515_1647x1421_scrot](https://user-images.githubusercontent.com/157609/36566394-ab61a35c-1823-11e8-9e1e-1d36d59f3e37.png)
And at Jenkins:
>  ![screen shot 2018-02-22 at 23 00 …
> Versioned Dev Builds for CI ✅

- .dockerignore
- .gitignore
- Dockerfile
- README.md
- add-on/manifest.json
- ci/firefox/index.html
- ci/firefox/update.json
- ci/update-manifest.sh
This PR closes #385, be sure to read that issue first as the Firefox context is bit complex:
Changes introduced in this PR:
- Normalize indentation of `manifest.json` (makes future diffing easier)
- Publish initial version of `update.json` (the manifest for self-hosted Beta Channel for Firefox) 
-  I enabled Github Pages for `master` branch which gave us a stable permalink: 
`https://ipfs-shipyard.github.io/ipfs-companion/ci/firefox/update.json`
- Created simple landing page that reads the manifest and displays a link to the latest Beta. 
- Advertising Beta channels in `README`:
- Beta for Firefox: Self-hosted Signed Dev Build (link will work after PR is merged)
- Beta for Chrome: [Dev Build at Chrome Web Store](https://chrome.google.com/webstore/detail/ipfs-companion-dev-build/hjoieblefck …
> Set Up Self-hosted Beta Channel for Firefox

- package.json
- yarn.lock
Ethereum dependencies were updated to fix the browserify config issues causing us to also need these dependencies to be installed in order to build.
https://github.com/ethereumjs/ethereumjs-block/pull/40
https://github.com/ethereumjs/ethereumjs-util/pull/119
\o/ yay we no longer have to install dependencies we don't use directly.
> Removes unused dependencies

- package.json
- yarn.lock
Currently the return type for `ipfs.swarm.peers` is different depending on whether we're talking directly to a js-ipfs or js-ipfs-api ([issue opened here](https://github.com/ipfs/js-ipfs/issues/1248)).
This PR updates the proxy to take this into account so that it doesn't error when passed a `PeerId` where it is expecting a `PeerInfo` (https://github.com/tableflip/ipfs-postmsg-proxy/commit/eb0aa43416ad79c4a84b0aaa48a035f54d4d6dae).
> Fixes ipfs.swarm.peers call when using js-ipfs-api

- add-on/manifest.firefox-58.json
- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- package.json
- test/functional/lib/ipfs-request.test.js
- yarn.lock
This PR implements changes described in https://github.com/ipfs-shipyard/ipfs-companion/issues/164#issuecomment-355708883, namely support for simplified (redirect-based) protocol handlers for  `dweb:` and `ipfs://` without `web+` prefix.  
It works perfectly fine with latest Firefox Nightly (59a1), but fails to load in Firefox <59:
```
$ web-ext run -s add-on/ --browser-console --verbose
[firefox/index.js][debug] Firefox stdout: 1516628484552	addons.webextension.<unknown>	ERROR	Loading extension 'null': Reading manifest: Error processing protocol_handlers.3.protocol: Value "dweb" must either: be one of ["bitcoin", "geo", "gopher", "im", "irc", "ircs", "magnet", "mailto", "mms", "news", "nntp", "sip", "sms", "smsto", "ssh", "tel", "urn", "webcal", "wtai", "xmpp"], or match the pattern …
```
> Protocol handlers without web+ prefix in Firefox 59

- add-on/src/lib/ipfs-proxy/request-access.js
- add-on/src/pages/proxy-access-dialog/index.js
I noticed this was still happening despite the previous "fix". I move the code for the fix into the page JS and it worked.
> fix: proxy access dialog display issue on Firefox

- add-on/src/options/options.css
- add-on/src/options/options.js
This PR aims to fix UI bug reported by @alanshaw:
- fix is to either specify `min-width` and `overflow` controls, or explicitly open `options_ui` page in a new tab
- `open_in_tab` is [being deprecated](https://developer.chrome.com/extensions/optionsV2#step-1), so we would have to do it manually
> ![screenshot-2018-3-21 options - google chrome](https://user-images.githubusercontent.com/157609/37718168-63be4e38-2d22-11e8-82bb-be836cf23cf0.png)
> Fix options_ui in OSX Chrome

- add-on/_locales/en/messages.json
- add-on/src/popup/browser-action/browser-action.css
- add-on/src/popup/browser-action/context-actions.js
- add-on/src/popup/browser-action/gateway-status.js
- add-on/src/popup/browser-action/header.js
- add-on/src/popup/browser-action/operations.js
- add-on/src/popup/browser-action/store.js
- add-on/src/popup/page-action/header.js
This PR aim to address the fact calculating pageActions for IPFS Paths is expensive (especially pin-related checks when pin is in progress).
- fixes and closes  #426 
- calculating pageActions states is expensive (especially pin-related checks when pin is in progress)
- pageActions are updated in a separate step to keep UI snappy
- experiment: add 800ms fade-in for dynamically added UI elements
- it may be subjective, but it eased the feel of 'erratic updates' a bit
- people do not focus on updates happening during fade-in 
- we can revert this change later, or replace basic fade-in with better animation
- demo (gif may render slower than realtime, but gives a good idea what is happening): 
> ![peek 2018-03-21 13-52](https://user-images.githubusercontent.com/157609/37710819-1d8e108c-2d0f-1 …
> Decouple Page Action Updates

- add-on/_locales/de_DE/messages.json
- add-on/_locales/en/messages.json
- add-on/_locales/es_ES/messages.json
- add-on/_locales/fr_FR/messages.json
- add-on/_locales/id_AC/messages.json
- add-on/_locales/id_ID/messages.json
- add-on/_locales/it_IT/messages.json
- add-on/_locales/pl_PL/messages.json
- add-on/_locales/ro_RO/messages.json
- add-on/_locales/ru_RU/messages.json
- add-on/_locales/sv_SE/messages.json
- add-on/_locales/zh_CN/messages.json
- add-on/src/lib/ipfs-companion.js
- add-on/src/popup/quick-upload.js
* Is now camel case: `NumObjects` -> `numObjects`
* Means that quick upload page now shows "and sharing 9497 files" again
* Removes `state.repoSize` as it's unused
> fix: object count

- add-on/src/lib/ipfs-proxy/index.js
- add-on/src/lib/ipfs-proxy/pre-acl.js
- add-on/src/lib/ipfs-proxy/pre-mfs-scope.js
- docs/window.ipfs.md
- package.json
- test/functional/lib/ipfs-proxy/pre-acl.test.js
- test/functional/lib/ipfs-proxy/pre-mfs-scope.test.js
- yarn.lock
https://youtu.be/KvgxAafphPg
See https://github.com/ipfs-shipyard/ipfs-companion/issues/330#issuecomment-367651787 for discussion.
To avoid conflicts, each app gets it's own MFS directory where it can store files. When using MFS functions (see [docs](https://github.com/ipfs/interface-ipfs-core/blob/master/SPEC/FILES.md#mutable-file-system)) this directory will be automatically added to paths you pass. Your app's MFS directory is based on the **origin and path** where your application is running.
e.g.
* `files.write` to `/myfile.txt` on `https://domain.com/`
* writes to `/dapps/https/domain.com/myfile.txt`
* `files.write` to `/path/to/myfile.txt` on `https://domain.com/feature`
* writes to `/dapps/https/domain.com/feature/path/to/myfile.txt`
* `files.read` from …
> feat: scope mfs calls to an application path

- package.json
- yarn.lock
This PR updates `ipfs-postmsg-proxy` to version 2.13.0 which adds support for `ipfs.name.*` and `ipfs.stats.*`.
> feat: upgrades ipfs-postmsg-proxy to 2.13.0

- add-on/src/lib/ipfs-proxy/request-access.js
This is a fix for the issue reported here: https://github.com/ipfs-shipyard/ipfs-companion/pull/442#pullrequestreview-110017486
This PR adds checks to the port connect and tab removed listeners to ensure that the tab that is connecting or being closed is the tab that they are in charge of!
To test:
```js
Promise.all([ipfs.id(), ipfs.files.ls(), ipfs.id(), ipfs.files.ls(), ipfs.files.ls()]).then(console.log).catch(console.log)
```
Expect 5 dialogs to open*, you should be able to respond to each one individually.
\* fix for multiple dialogs for the same permission is coming soon in #442
> fix: response for multiple acl dialogs get mixed up

- add-on/src/popup/browser-action/store.js
This PR is a rebased version of https://github.com/ipfs-shipyard/ipfs-companion/pull/355, hopefully closes #318 
I do not own a Mac, so re-assigning to @olizilla  who noticed it in https://github.com/ipfs-shipyard/ipfs-companion/issues/318#issuecomment-378579068
> Fix popup render issue in Chrome on Mac

- README.md
- add-on/manifest.common.json
- move badge hosting to IPFS
- version bump to v2.2.1 (so that dev builds are in front of stable channel)
- updated author in manifest.  `about:addons` now looks like this:
>  ![screenshot_16](https://user-images.githubusercontent.com/157609/38563126-6bf123a4-3cdc-11e8-94bd-b521a04c1c4c.png)
> Post release chores

- package.json
- yarn.lock
This fixes a problem with the DAG node/link and Block dependencies not yet having a `isDAGNode` etc. function.
> fix: updates ipfs-postmsg-proxy to version 2.14.0

- package.json
- yarn.lock
This PR upgrades ipfs-postmsg-proxy to 2.15.0 with support for the bootstrap API and the additional (but not yet spec'd) bitswap API methods.
This brings it as close to interface-ipfs-core compatible as it can be right now barring the resolution of https://github.com/ipfs/js-ipfs/pull/1297
> feat: updates ipfs-postmsg-proxy to 2.15.0

- add-on/src/contentScripts/ipfs-proxy/content.js
- package.json
- yarn.lock
There were two issues at play here:
1. `pull-postmsg-stream` was using an old version of `postmsg-rpc` so wasn't getting the data from a message correctly and caused it to error when pulling over web extension port messaging
2. Companion was actively disallowing bi-directional messages. For pull streams to work, messages need to flow in both directions
> fix: window.ipfs streaming

- .travis.yml
- add-on/src/contentScripts/ipfs-proxy/page.js
This PR decreases size of `add-on/dist/contentScripts/ipfs-proxy/` by 1.7MB  (60%)
Context:
https://github.com/ipfs-shipyard/ipfs-companion/issues/460#issuecomment-384225346
> Remove API client constructor from window.Ipfs

- README.md
- add-on/_locales/en/messages.json
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/forms/ipfs-node-form.js
- add-on/src/options/options.css
- docs/node-types.md
This PR is is trying to address onboarding issues raised in: https://github.com/ipfs-shipyard/ipfs-companion/issues/470 (cc @slrslr)
It adds `docs/node-types.md` doc (see doc [preview](https://github.com/ipfs-shipyard/ipfs-companion/blob/1430b3a74d48432f731216386c2af2fb9e11e4ca/docs/node-types.md)) and  links to it from _Preferenses_ screen:
It also adds similar link for `docs/window.ipfs.md`, which already existed, but was impossible to discover from _Preferences_ screen.
> Add docs about Node Types

- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
This PR forces blocking `webRequest` hooks to explicitly skip initial HTTP requests related to websocket [protocol upgrade](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism)  (HTTP2IPFS gateways do not support WSS anyway). That way we will be immune to ephemeral bugs such as one mentioned in #469 and won't break hybrid websites. 
Both Chrome and Firefox (nightly and stable) include it in mentioned scope and pass it to both hooks: 
> | Firefox | Chrome |
> | --- | --- |
> | ![screenshot_1](https://user-images.githubusercontent.com/157609/39519547-776be994-4e07-11e8-8103-54c865caced2.png)  |  ![screenshot_6](https://user-images.githubusercontent.com/157609/39519490-3b92660a-4e07-11e8-8997-e478f141f5df.png) |
Closes #469
> Skip HTTP GET of websocket handshake

- README.md
- ci/update-manifest.sh
- docs/developer-notes.md
- package.json
This PR automates tasks for building firefox and chrome bundles for 'stable' and 'beta'
channels by adding high-level all-in-one targets:
- `npm run dev-build` -- all-in-one for local development: fast dependency install and build with yarn (**update** yarn.lock if needed)
- `npm run beta-build` -- reproducible beta build in docker with **frozen** yarn.lock
- `npm run release-build` -- reproducible release build in docker with **frozen** yarn.lock
Scripts take care of updating `add-on/manifest.json` and provide docker orchestration necessary for achieving reproducible build (#306) across platforms.
> Add release scripts

- ci/Jenkinsfile
This  PR adds a dev-build for Windows to act as a a smoke-test to ensure we don't break build on that platform. 
I also added parallel MacOS build (it does not increase build time).
> CI smoke-test build or Windows

- package.json
`shx` did not work correctly and we did not get proper bundle for Firefox.
This PR fixes it. Also, submitting as a PR to see if it does not break Windows build.
> fix: correct manifest for firefox beta bundle

- add-on/_locales/en/messages.json
- add-on/src/popup/quick-upload.js
- package.json
- yarn.lock
when js-ipfs is used, progress is provided in realtime (js-ipfs-api displays buffering state for the most of time):
Creating a sparse file (filled with zeroes) of arbitrary size:
truncate -s 128m 128m.file
Big files filled with zeroes are handy for tests with js-ipfs, which has a limited repo store size (one chunk will just be reused).
> Upload screen feedback and bugfixes

- add-on/src/contentScripts/ipfs-proxy/content.js
- add-on/src/lib/ipfs-proxy/api-whitelist.json
- add-on/src/lib/ipfs-proxy/index.js
- add-on/src/lib/ipfs-proxy/pre-api-whitelist.js
- test/functional/lib/ipfs-proxy/pre-api-whitelist.test.js
- fix: restrict window.ipfs to Secure Contexts  (closes #476, closes #475)
- fix: introduce global whitelist for window.ipfs (closes #478,  mitigates #452)
- **Note:** This is a temporary measure we need to ship ASAP to mitigate risk until we move API whitelist to ipfs-postmsg-proxy and stop exposing methods at all (as noted in https://github.com/tableflip/ipfs-postmsg-proxy/issues/29)
@olizilla  please take a look, I want to merge this today :racehorse:
> Improving security of window.ipfs (low hanging fruits)

- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request.test.js
This PR disables gateway redirect for cross-origin XHRs.
- It fixes all the websites broken by [CORS false-positive bug in Firefox](https://github.com/ipfs-shipyard/ipfs-companion/issues/436#issuecomment-378254294) (samples below).
-  It is a "lesser evil". There will be no gateway redirect for such requests, but at least "IPFS-enabled" websites that do cross-origin requests to different gateways will work.
- I believe we want the same behavior on all browsers, so initial version of this PR conforms to the Firefox limitation in Chrome as well.
- For: Different handling on different browsers would be a nightmare for a developer, who assumes it "works the same everywhere". 
- Against: We introduce artificial limitation for browsers other than Firefox.
- The full context is in …
> Do not redirect XHR that would fail due to CORS bug in Firefox

- README.md
- package.json
Following convention from https://github.com/ipfs/pm/issues/600, 
it may make it easier for potential contributors to reach out for help if they know who is the maintainer.
> Add Lead Maintainer

- add-on/manifest.firefox.json
- add-on/src/contentScripts/ipfs-proxy/content.js
- add-on/src/lib/ipfs-companion.js
This PR enables Firefox users to disable creation of `window.ipfs` attribute via _Preferences_ screen, solving fingerprinting issue raised in #451.
It requires webpack, so should be merged after #498 
Existing `tabs.executeScript` API with `runAt: 'document_start'` flag was executing too late and page scripts were  unable to detect `window.ipfs` correctly.  More info on the underlying issue: #368 https://github.com/ipfs-shipyard/ipfs-companion/issues/362#issuecomment-362231167
As a workaround that worked in both Chrome and Firefox, we were forced to always load content script via manifest definition. This meant no control over when it is loaded and no easy off switch. If `window.ipfs` was disabled via _Preferences_, it was throwing an Error on access, but remained in the scope.
Mozilla …
> feat: disable creation of window.ipfs attribute

- add-on/src/popup/browser-action/icon.js
This PR fixes a problem that happened in Chrome (Mac). 
As we hovered the icons they scaled a bit so it had a weird behaviour:
I've removed the scale effect, as it was minor and the changing background color is more than sufficient from an UX point of view:
> fix: icons hover

- add-on/src/contentScripts/linkifyDOM.js
- webpack.config.js
This PR updates very old content script responsible for making plain text IPFS paths clickable.
- Support dynamic JS apps by rate-limiting operations via global job queue
- Run only one DOM-mutating task at the time
- Ignore DOM nodes under a parent with  `contentEditable` property equal true
- This fixes heavily customized input fields on Slack and Twitter and closes #503
> fix: rate-limiting the Linkify experiment

- add-on/src/lib/ipfs-companion.js
- add-on/src/popup/quick-upload.js
This PR:
- provides a fix for a bug described in https://github.com/ipfs-shipyard/ipfs-companion via workaround from https://github.com/ipfs/go-ipfs/issues/5168#issuecomment-401417420
- **TL;DR** Browser extension is able to detect requests to `/api/v0/add` and set `Connection: close`
- moves core upload logic from background page to `quick-upload` page
> Workaround for  the 'invalid Read on closed Body'  bug in HTTP API

- README.md
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request.test.js
**TL;DR**: this PR adds support for `x-ipfs-no-redirect` symbol as a way to disable gateway redirect for a single request, without disabling anything globally.
https://ipfs.io/ipfs/QmbWqxBEKC3P8tqsKc98xmWNzrzDtRLMiMPL8wBuTGsMnR#x-ipfs-no-redirect
```js
function isSafeToRedirect (request, runtime) {
// Do not redirect if URL includes opt-out hint
if (request.url.includes('x-ipfs-no-redirect')) {
return false
}
```
That is all. The rest is just some cleanup/refactoring without any functional changes.
This PR adds an URL-based opt-out from global gateway redirect that website developers can rely on  to ensure request goes to the specific HTTP gateway.
Potential consumers of this feature:
- Public gateway preloaders (IPFS Companion already does this for uploads)
- Health checks (eg. …
> Redirect Opt-out via URL Hints

- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request.test.js
This PR supersedes https://github.com/ipfs-shipyard/ipfs-companion/pull/422 and adds a useful error page for rare cases when redirect-based URI handler was unable to process URI.
Note that redirect-based handler is specific to Firefox  as Chrome does not support `manifest.json/protocol_handlers`. 
In my experience this specific type of error is displayed only when someone is playing with protocol handler and enters address by hand to the address bar and makes a typo or puts `foobar` as a CID.
> ![screenshot_2](https://user-images.githubusercontent.com/157609/41740922-d30092be-7599-11e8-9384-1532f68538c5.png)
Opening `ipfs://invalid-cid` redirected  to https://ipfs.io/#redirect/ipfs%3A%2F%2Finvalid-cid, but because `invalid-cid` is not a valid IPFS resource, it was not redirected further. …
> feat: meaningful error in redirect-based URI handler

- README.md
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request.test.js
This is a tweak of https://github.com/ipfs-shipyard/ipfs-companion/pull/505, as suggested in https://github.com/ipfs-shipyard/ipfs-companion/pull/505#issuecomment-401723828
> Change redirect opt-out to `x-ipfs-companion-no-redirect`

- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request.test.js
This PR restores gateway redirect for CORS XHR in Firefox via late redirect in `onHeadersReceived` and closes #436.
Context for why CORS XHR were not redirected until now can be found in https://github.com/ipfs-shipyard/ipfs-companion/issues/436#issuecomment-378254294 and upstream [Bug #1450965](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965). 
In short, `onBeforeRequest` can't redirect anything when CORS XHR is processed, otherwise it will trigger false-positive CORS error.  Good news is that `onHeadersReceived` is executed  long after CORS validation happens in Firefox, and allows us to cancel original connection and do a late redirect right after response headers arrive. 
This is the best we can do until upstream [Bug #1450965](https://bugzilla.mozilla.org/show_bug.cgi?id=1450965) …
> Restore gateway redirect for CORS XHRs in Firefox

- add-on/_locales/en/messages.json
- add-on/src/lib/context-menus.js
- add-on/src/lib/ipfs-companion.js
#513 
Very simple addition so you can upload files that are linked to on a page. For example pdf files so you do not have to download them and manually upload them. 
A current problem I noticed is that when trying to upload links directly from google search results it opens a print dialog. This seems be fixed when using an extension that removes google redirect links. https://addons.mozilla.org/en-US/firefox/addon/google-no-tracking-url/?src=search
> Add support for uploading files linked to on a page, using the context menu

- add-on/src/lib/dns-link.js
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request.test.js
Dnslink lookup is disabled by default, but if user opted-in in latest version websites were broken due to false-positive late gateway redirects of XHR requests.
This PR  fixes dnslink regression introduced by https://github.com/ipfs-shipyard/ipfs-companion/pull/511
and adds tests to guard against the problem in future.
Some deeper refactoring is due, but that is something for separate PR.
I want to land this PR as soon as possible, so that dnslink works again.
> Fix XHR redirects when dnslink is enabled

- README.md
- test/data/linkify-demo.html
- swapped GIF to reflect UI changes in  v2.4.x
- node type moved to experiments
- added linkify demo page
→ [README PREVIEW](https://github.com/ipfs-shipyard/ipfs-companion/blob/23585ebfc3f1d8fc2764123ae8bf2bb9f19acf51/README.md#ipfs-companion)
> chore: update README to reflect v2.4.x

- package.json
- webpack.config.js
- yarn.lock
Default minimizer flags break pubsub with embedded node  by removing 'unused' code of pubsub experiment. Details in #521.
-  Backport of https://github.com/ipfs/aegir/pull/214: it restores pubsub functionality and applies the fix for  entire build pipeline to avoid similar issues in future.
- The way configuration blocks are merged is improved by use of [webpack-merge](https://www.npmjs.com/package/webpack-merge)
- Bundles are bit smaller due to moving LICENSE comments to separate file (`extractComments: true`)
- Closes #521
> Change webpack minimizer flags to follow Aegir

- add-on/src/lib/dns-link.js
- test/functional/lib/dns-link.test.js
This PR: 
- ensures dnslink redirect to `/ipns/{fqdn}/{path}` does not happen for `/ipfs/`, `/ipns/` and `/api/` paths
- adds proper dnslink tests
Public gateways are often exposed under the same domain name  (https://ipfs.io) and even
tho right now CID-based redirect takes precedence things could break if we ever do some refactoring and move things around. 
Rare edge cases which are fixed by this PR:
- https://ipfs.io/api/v0/dns/ipfs.io  broken due to dnslink triggering redirect to `/ipns/`.
- https://ipfs.io/ipfs/invalid_cid in which no valid CID is detected, so path is marked as non-ipfs and dnslink redirect skews original error.
> Exclude gateway paths from dnslink redirects

- add-on/src/lib/ipfs-proxy/pre-mfs-scope.js
- test/functional/lib/ipfs-proxy/pre-mfs-scope.test.js
> window.ipfs.files.cp|mv fixes

- add-on/src/contentScripts/linkifyDOM.js
For historical reasons Linkify was wrapping false-positives (things that look like /ipfs/ paths  but have invalid CID) in `<span class..>` to ignore them in future. 
This behavior breaks some snippets, as noted in #539.
Good news is that since that was created, we've added IPFS validation lookup cache and `<span>` is no longer necessary.  
Note to self: in the long run we'll need e2e integration tests that run content script against sample page in a real browser.
Closes #539  (including https://github.com/ipfs-shipyard/ipfs-companion/issues/539#issuecomment-407938115)
> fix(linkify): do not wrap / ignore false-positives

- add-on/src/popup/browser-action/store.js
In past `ipfs.name.resolve` returned object with `Path` field, right now it returns a path as a string.
Closes #542
> fix: pinning of IPNS paths

- add-on/src/popup/quick-upload.js
- package.json
- yarn.lock
This PR restores drag&drop support and closes #549.
(Looks like it got removed during one of refactorings)
- directory upload is not possible at this time, we detect it and display error message instead
- empty file without extension looks the same as empty directory, so the error accounts for that possibility
- account for edge cases where the source of dragged object is not valid, which results in drag&drop event with empty file list
> fix: drag & drop uploads

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-workarounds.test.js
> Chrome does allow setting `Expect` via [`onBeforeSendHeaders`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/webRequest/onBeforeSendHeaders) WebExtension API
This means we now have a workaround for https://github.com/ipfs-shipyard/ipfs-companion/issues/480 that works in both Firefox and Chromium.
Details: https://github.com/ipfs-shipyard/ipfs-companion/issues/480#issuecomment-417657758 & https://github.com/ipfs/go-ipfs/issues/5168#issuecomment-417112652
Closes #480
> Workaround for 'invalid Read on closed Body' in files.add (webext in Chrome)

- add-on/src/popup/browser-action/store.js
Path passed to `ipfs.pin.add` should not include hash or query segment.
This PR:
- Sanitizes path by getting it from URL via `new URL(url).pathname`
- Closes: https://github.com/ipfs-shipyard/ipfs-companion/issues/567
> fix: pin URL with hash or query

- package.json
- yarn.lock
This PR closes https://github.com/ipfs-shipyard/ipfs-companion/issues/485 thanks to the fix from https://github.com/tableflip/ipfs-postmsg-proxy/pull/35 (thanks @alanshaw!)
> fix: slow window.ipfs.files.add in Firefox

- add-on/src/lib/dnslink.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-path.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/options.js
- add-on/src/lib/state.js
- add-on/src/options/forms/api-form.js
- add-on/src/options/forms/gateways-form.js
- add-on/src/options/page.js
- test/functional/lib/dnslink.test.js
- test/functional/lib/ipfs-request-gateway-redirect.test.js
1. Small cleanup of the way we construct destination URL:
Previously URL was created by hand in multiple places,
this change introduces `pathAtHttpGateway(path, gateway)`
utility and reuses it in all those places.
2. As a result, It is now possible to set local gateway URL to http://localhost/ (Chrome will not mangle it into http://localhost:0/)
Closes https://github.com/ipfs-shipyard/ipfs-companion/issues/580
3. UX improvement: allow training slash in URL inputs on Preferences screen
> fix: support gateway at localhost:80

- add-on/src/popup/browser-action/store.js
> `ipfs swarm peers` should be fast, `ipfs pin ls` may get really slow for mid-large repos, especially when called without `-t recursive` flag (mine repo has few 100k's of pins, pin ls can take minutes to finish)
As a workaround until #415  lands we only check for explicit (recursive) ones,
as suggested in https://github.com/ipfs-shipyard/ipfs-companion/issues/360#issuecomment-380631986
Closes #360
> Fix random UI glitches: check only for recursive pins

- add-on/_locales/en/messages.json
- add-on/src/lib/context-menus.js
- add-on/src/lib/copier.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-path.js
- add-on/src/popup/browser-action/context-actions.js
- add-on/src/popup/browser-action/page.js
- add-on/src/popup/browser-action/store.js
- add-on/src/popup/page-action/page.js
- package.json
(Closes #579, https://github.com/ipfs-shipyard/ipfs-companion/issues/592, https://github.com/ipfs-shipyard/ipfs-companion/issues/599)
I played a bit with the concept from #579 and it is not enough to change the order.
Instead we should have clear, separate labels for each context. So far I've added a separate menu item for adding link destination and kept common label for images,videos and audio as "Add This Object to IPFS".
Screenshot below illustrates the most extreme case is when you select part of a page and then click on an image that is also a link (so you get actions for all those contexts):
> ![screenshot_28](https://user-images.githubusercontent.com/157609/45722588-5be0de00-bbad-11e8-900d-7823f4de383d.png)
@alanshaw  @olizilla  would appreciate quick review of _"Add ... to IPFS"_ …
> Improvements for Adding to IPFS via Context Menu

- add-on/_locales/cs/messages.json
- add-on/_locales/da/messages.json
- add-on/_locales/de/messages.json
- add-on/_locales/es/messages.json
- add-on/_locales/fr/messages.json
- add-on/_locales/hu/messages.json
- add-on/_locales/id/messages.json
- add-on/_locales/it/messages.json
- add-on/_locales/nl/messages.json
- add-on/_locales/no/messages.json
- add-on/_locales/pl/messages.json
- add-on/_locales/pt/messages.json
- add-on/_locales/ro/messages.json
- add-on/_locales/ru/messages.json
- add-on/_locales/sv/messages.json
- add-on/_locales/zh_CN/messages.json
Transifex released a new Chrome i18n parser ensuring that i18n
placeholders are preserved upon export.
I migrated resource at the crowdsourcing site, and pulled resources
produced by the new parser into this commit.
It brings a big change set but it is [mostly whitespace](https://github.com/ipfs-shipyard/ipfs-companion/pull/606/commits/d8b1bdf6b6ae8dc81ee901647b54e449371a5189?utf8=%E2%9C%93&diff=split&w=1).
> chore: switch to the new i18n parser

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-gateway-redirect.test.js
- Ignored requests are identified early and cached across all
[`browser.webRequest.*` hooks](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest)
- Global toggle now correctly disables all hooks and workarounds
- Tests now use `expectNoRedirect` which checks both `onBeforeRequest` and `onHeadersReceived`
- Closes #604
> Fix edge cases around localhost redirects

- package.json
- yarn.lock
This PR solves problem described in https://github.com/ipfs-shipyard/ipfs-companion/issues/360#issuecomment-427525801 by applying fix for ipfs-api from https://github.com/ipfs/js-ipfs-api/pull/875
Closes #360
> fix: pin.ls ignored opts when hash was present

- package.json
- yarn.lock
This PR switches to js-multiaddr from https://github.com/multiformats/js-multiaddr/pull/71 and fixes error from https://github.com/ipfs-shipyard/ipfs-webui/issues/878  when ipfs-webui is used with API instance from ipfs-companion. 
A lot of people will may be playing with QUIC which currently breaks Web UI and various other dapps, 
so  I am fast-tracking this to beta channel as a bugfix release as a band-aid until the proper fix is merged upstream.
> fix: add support for quic multiaddrs

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-workarounds.test.js
This PR restores [this workaround](https://github.com/ipfs-shipyard/ipfs-companion/blob/7a6fac1d9dc344b426120e121e158d220d377be5/add-on/src/lib/ipfs-request.js#L153-L161) for localhost API closes #615
(Fast tracking as this needs to land in Beta and Stable)
> fix: CORS false-positive in Chrome 71

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-gateway-redirect.test.js
This is a fix of a regression for https://github.com/ipfs-shipyard/ipfs-companion/pull/537 that was introduced when a redirect based on the presence of `X-Ipfs-Path` header support got added.
Until we are able to provide the same origin-based security guarantees at a local gateway, we should not redirect resources that use  cid-in-subdomain deployment (https://github.com/ipfs/in-web-browsers/issues/89), as it is a strong hint they care about Origin-based isolation and we should not relax those guarantees.
> Disable redirect for CID-in-subdomain even when X-Ipfs-Path is present

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-workarounds.test.js
- yarn.lock
Closes https://github.com/ipfs-shipyard/ipfs-companion/issues/622
Context: https://github.com/ipfs-shipyard/ipfs-companion/issues/622#issuecomment-439418474
---
FUN FACT: underlying `URL.origin` value depends on actual runtime
Node 8: 
```js
new URL('moz-extension://0f334731-19e3-42f8-85e2-03dbf50026df/').origin === 'null'
```
Firefox Firefox-65.0a1:  
```js
new URL('moz-extension://0f334731-19e3-42f8-85e2-03dbf50026df/').origin === 'moz-extension://0f334731-19e3-42f8-85e2-03dbf50026df'
```
Tests and code is value-agnostic, but it is worth being aware that [url spec](https://url.spec.whatwg.org/) and implementations often diverge around edge cases.
> fix: Origin in API calls in Firefox-65.0a1

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-workarounds.test.js
WebExtension running in background context of Chromium Beta 72 sends `Origin: chrome-extension://{uid}` which triggers false-positive Forbidden 403 in go-ipfs
Closes https://github.com/ipfs-shipyard/ipfs-companion/issues/630:
> fix: Origin in API requests under Chromium 72

- docs/x-ipfs-path-header.md
I found it hard to understand the `x-ipfs-path` readme and took a shot at rephrasing some of the documentation. It's a small change but it, hopefully, helps the next newbie to more easily understand the `x-ipfs-path` header.
I am not a native English speaker myself so I hope I slightly improved the copy and didn't make it worse. :wink:
> Copy improvements for x-ipfs-path documentation

- add-on/src/lib/ipfs-client/index.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-proxy/access-control.js
- add-on/src/lib/ipfs-request.js
- add-on/src/popup/quick-upload.js
This PR adds support for backends before and after breaking change introduced in https://github.com/ipfs/interface-ipfs-core/pull/378 by manually adding the new version in case old backend is used.
> fix: support ipfs.add and ipfs.files.add

- add-on/src/lib/ipfs-client/external.js
This commit fixes the issue that a protocol name (http or https) is not passed to `ipfs-http-client` as intended.
Closes #652
> fix: support HTTPS API endpoints

- add-on/src/lib/ipfs-client/index.js
- test/functional/lib/ipfs-companion.test.js
> Continuation of https://github.com/ipfs-shipyard/ipfs-companion/pull/651
This change makes `window.ipfs` (ipfs-postmsg-proxy) work with both old and new APIs by aliasing old command to the new one, fixing the bug below:
> fix: missing Files APIs over window.ipfs

- add-on/src/popup/browser-action/operations.js
- package.json
- yarn.lock
This PR enables Web UI with embedded js-ipfs node.
In the past ipfs-webui crashed due to missing APIs (IPNS, MFS) or misaligned CID/multiaddr versions, but recent version works quite nicely:
Parking this PR until js-ipfs v0.34.0 officially lands :)
cc @alanshaw
> feat: enable bundled Web UI for embedded js-ipfs

- add-on/manifest.brave.json
- package.json
These changes makes it so a bundle for Brave can be created which have chrome.socket APIs exposed. 
Note that `key` manifest JSON property is needed to get a consistent
extension ID when developing across machines.  Since the APIs are only whitelisted for this extension ID, this is needed. 
If you're wondering where the `key` manifest JSON property value can be obtained from, you can get it by installing IPFS Companion from the Chrome store and looking in your profile directory at the written manifest.  For example, on macOS it would be here: `~/Library/Application\ Support/BraveSoftware/Brave-Browser-Dev/Default/Extensions/nibjojkomfdiaoajekhjakgkdhaomnch/2.7.0_0/manifest.json`
This will not work with the current live release of Brave, however you can build a new `ipfs` branch that I …
> Add bundle:brave npm script and Brave manifest

- package.json
- yarn.lock
js-ipfs [v0.32.2](https://github.com/ipfs/js-ipfs/releases/tag/v0.34.2) solved issue mentioned in https://github.com/ipfs-shipyard/ipfs-share-files/issues/63#issuecomment-444565592 by switching to `libp2p-websocket-star-multi` (details in https://github.com/ipfs/js-ipfs/issues/1793).
> feat: use ws-star-multi instead of ws-star

- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/state.js
- add-on/src/popup/browser-action/operations.js
- add-on/src/popup/browser-action/store.js
- package.json
- scripts/fetch-webui-from-gateway.js
- test/functional/lib/ipfs-request-workarounds.test.js
- webpack.config.js
- yarn.lock
> This is a prerequisite for  #679, so **I am merging in fast-track mode to create a new release and fix #679 ASAP**.
>  Feel free to comment – will address any concerns in separate PRs. 
Before, webui was bundled with extension itself. Unfortunately this
caused issues with reviews at addon (webui build was not reproducible).
**This PR replaces bundled webui with one loaded from custom gateway.**
- To make it work we modify HTTP headers to make cross-origin requests
from 'blessed' webuiRootUrl work without changing default go-ipfs configuration.
- To improve UX, content script sets `ipfsApi` in webui's `localStorage`
to the same endpoint as one defined in Companion (unless it was already
customized by the user).
- Switched programmatic content script injections from …
> feat: load Web UI from IPFS

- README.md
- docs/privacy-policy.md
This PR adds Privacy Policy in Markdown format (to make it easier to maintain and audit)
- human-readable permalink: https://ipfs-shipyard.github.io/ipfs-companion/docs/privacy-policy
- change history: https://github.com/ipfs-shipyard/ipfs-companion/commits/master/docs/privacy-policy.md
Merging this as-is: Privacy Policy was reviewed by legal, any changes to existing Privacy Policy text need to be submitted as separate PR.
> Add Privacy Policy

- add-on/src/options/forms/api-form.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/forms/gateways-form.js
- add-on/src/options/forms/global-toggle-form.js
- add-on/src/options/options.css
- add-on/src/pages/components/switch-toggle.css
- add-on/src/pages/components/switch-toggle.js
- add-on/src/popup/browser-action/browser-action.css
- add-on/src/popup/browser-action/nav-item.js
This PR is implementing some feedback from #689:
- updated colors based on suggestion from @ericronne  https://github.com/ipfs-shipyard/ipfs-companion/issues/689#issuecomment-469727482
- off state is `7f8491` (`charcoal-muted` from [ipfs-css](https://github.com/ipfs-shipyard/ipfs-css))
| on/on/off | off/disabled/on |
| ---- | ---- |
| ![2019-03-06--14-57-50](https://user-images.githubusercontent.com/157609/53887351-5e7fa480-4022-11e9-8fac-631beaa9e3b4.png) | ![2019-03-06--15-03-21](https://user-images.githubusercontent.com/157609/53887367-64758580-4022-11e9-801b-b6d28cc6732e.png) |
- Replaced checkboxes on _Preferences_ screen:
> ![2019-03-06--14-56-36](https://user-images.githubusercontent.com/157609/53887295-4871e400-4022-11e9-8935-952bf1b6a0b9.png)
- fixed CSS for checked/disabled
> Toggle Switch Tweaks

- add-on/src/lib/copier.js
- add-on/src/lib/dnslink.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-path.js
- add-on/src/lib/ipfs-request.js
- add-on/src/popup/browser-action/store.js
- package.json
- test/functional/lib/dnslink.test.js
- test/functional/lib/ipfs-path.test.js
- test/functional/lib/ipfs-request-dnslink.test.js
- test/functional/lib/ipfs-request-gateway-redirect.test.js
- test/functional/lib/ipfs-request-protocol-handlers.js
- test/functional/lib/ipfs-request-workarounds.test.js
- yarn.lock
> cc #689 
When we introduced option to opt-out from redirect per site (#687 ) it came with a side effect of removing IPFS context actions. 
This PR:
-  Adds context actions on DNSLink sites (when redirect is disabled)
>  This adds context actions such as "Copy IPFS path", "Copy CID", "Pin" to DNSLink websites without redirect. 
> 
> It includes refactoring of ipfsPathValidator to expose high level resolvers used in various places by the Companion:
> 
> - `resolveToPublicUrl`: always return a meaningful, publicly accessible URL that can be accessed without the need of IPFS client.
> - `resolveToIpfsPath`: return a valid IPFS path that can be accessed with IPFS client.
> - `resolveToImmutableIpfsPath`: same as resolveToIpfsPath, but the path is always immutable /ipfs/
> - `resolveToCid`: …
> Show IPFS Actions on DNSLink Sites

- add-on/src/popup/browser-action/context-actions.js
This removes flashing/jitter during pinning caused by brief
disabled/enabled state change.
(Since we now have a toggle, there is no need for disabling the toggle during pinning/unpinning states)
> Fix flashing of pin/unpin toggle

- package.json
- yarn.lock
This fixes regresssion of #654 introduced by `ipfs-http-client` by replacing both `stream-http` and old versions of `iso-stream-http` with the latest one. 
Upstream details: https://github.com/ipfs/js-ipfs-http-client/issues/959
Closes #706
> fix: support HTTPS API endpoint

- .babelrc
- add-on/manifest.firefox.json
This change updates minimal version in manifest, so new releases will not break Firefox ESR.
Browserfied js-ipfs-http-client does not seem to work as expected in Firefox <65 
(`TypeError: response.body is undefined` due to [this line](https://github.com/hugomrdias/iso-stream-http/blob/98e9e59718fcdc6f869bd2bc60641719357fe66b/lib/incoming-message.js#L71), probably due to lack of Streaming APIs).
I confirmed v2.7.5 of ipfs-companion works fine, so I marked all following releases to require 65.0 or later, making the last working version the default for ESR users.
ESR userbase is small enough (~5% of firefox users) to just wait for the next ESR scheduled to land in July.
> Require Firefox 65.0

- add-on/_locales/en/messages.json
- add-on/src/background/background.js
- add-on/src/landing-pages/welcome/store.js
- add-on/src/lib/context-menus.js
- add-on/src/lib/dnslink.js
- add-on/src/lib/ipfs-client/embedded-chromesockets.js
- add-on/src/lib/ipfs-client/embedded.js
- add-on/src/lib/ipfs-client/external.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-proxy/enable-command.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/on-installed.js
- add-on/src/lib/options.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/page.js
JS IPFS ecosystem is using [debug](https://www.npmjs.com/package/debug) for logs.
This PR supersedes #557 and adds support for latest `debug` in IPFS Companion:
- Replaced `console.log` calls with  debug-based `log` and `log.error`
- Different parts of extension and JS IPFS stack log to own namespaces
- User can tweak which logs should be printed to Browser Console using input on Preferences screen:
> ![2019-04-16--23-42-32](https://user-images.githubusercontent.com/157609/56246151-775b8b00-60a1-11e9-98a9-0756e4a191e3.png)
- Setting _Log Level_ to `*` will show all logs:
> ![2019-04-16--23-42-51](https://user-images.githubusercontent.com/157609/56246164-7d516c00-60a1-11e9-913c-1454603084ca.png)
- If _Embedded_ node is used logs will include low level libp2p:
> …
> Support configurable logger namespaces

- add-on/_locales/en/messages.json
- add-on/src/landing-pages/welcome/page.js
This PR adds info about IPFS Desktop to the welcome page introduced in #565.
The Welcome Screen appears once, after initial install from add-on store.
I also fixed/tweaked some links to give a better onboarding experience.
TERMINAL OR DIE
Terminal is life, but now there are options for everyone! :^)
@olizilla @ericronne  feel free to tweak copy if it can be worded in a  better way.
> feat(ux): suggest ipfs-desktop when no node is found

- .babelrc
- add-on/manifest.common.json
- add-on/manifest.firefox.json
I am not entirely sure this came to the correct spot as there are no examples that I could see and I think `incognito` could logically be a permission. 
Requested in https://github.com/ipfs-shipyard/ipfs-companion/issues/704#issuecomment-478929763. Closes #704
> manifest.common.json: disallow running in incognito mode

- add-on/src/lib/ipfs-client/embedded-chromesockets.js
- add-on/src/lib/ipfs-companion.js
- package.json
- yarn.lock
> Part of the effort to run embedded js-ipfs in Brave :lion: https://github.com/ipfs-shipyard/ipfs-companion/issues/716
fix(brave): no port collisions
Before starting embedded js-ipfs we now check if API and Gateway ports are free.
If not, we find available ones and update the config.
This way user does not need to deal with "port taken" errors and
embedded node provides seamless experience without surprises.
fix(brave): persist External node config
Embedded node used same config keys as External one. 
When switching between External and Embedded in Brave
we now persist the old (External) config and restore it when user
switched back to External node type.
> Fix port collisions in Brave

- add-on/src/lib/ipfs-client/index.js
- add-on/src/lib/state.js
This PR updated webui to [v2.4.7](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.7) introduces a simple optimization: preloads the root CID after IPFS Client start to speed up the first time Web UI is opened. This is a best-effort version of #682 that respects user bandwidth and does not fetch entire Web UI when extension starts.
If embedded js-ipfs is used (eg. in Brave #716) it will trigger a remote (always recursive) preload of entire DAG to one of preload nodes. This way when embedded node wants to load resources related to webui it will get them fast from preload nodes.
> feat: preload webui root CID

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-protocol-handlers.test.js
- fix: redirect-based handler vs no redirect on ipfs.io 
> Disabling redirect does it for all subdomains. We use gateway.ipfs.io as intermediate step when handling `ipfs://` in firefox, which resulted in a bizzarre edge case. 
This change restores `ipfs://` handler when redirect on ipfs.io is
disabled.
-  feat: support ipfs://{dnslink} (implements consensus from https://github.com/ipfs/in-web-browsers/pull/150#issuecomment-517953473)
> This adds support for resolving DNSLink via `ipfs://` protocol handler For now it is just a redirect to proper `/ipns/{dnslink}` path, but opens a way to improve UX in the long run.
Closes #534
>  feat: support ipfs://{dnslink}

- add-on/src/landing-pages/welcome/page.js
- add-on/src/landing-pages/welcome/store.js
- add-on/src/landing-pages/welcome/welcome.css
Demo of the proposal in issue #763. Personally, I think that this feature should be included because it provides a quick and obvious way to open the web ui.
closes #763
> feat: add 'Open Web UI' button to the welcome page

- add-on/src/lib/ipfs-companion.js
On Firefox forks the `runtime.isFirefox` detection will fail (because the browser name is not 'Firefox'). This leads to an error when registering webRequest listeners as the `extraHeaders` option is not needed, preventing the extension from loading.
There is actually an extension API that can be used to detect support for this option: [`OnBeforeSendHeadersOptions`](https://developer.chrome.com/extensions/webRequest#type-OnBeforeSendHeadersOptions).
This PR updates the feature detection check to explicitly look for this API. We have to also check to for the presence of `OnBeforeSendHeadersOptions` as it does not exist on Edge.
> fix: Improve extraHeaders feature detection

- add-on/src/lib/ipfs-companion.js
- package.json
- yarn.lock
This PR:
- Checks if browser action icon really changed. We now set it only when it is really needed, removing the overhead of redraw and internal requests
- Chrome does not support SVG in browser action, so we have to compute the path of raster  version (PNG). This needs to be done only once, so the calculation is now memoized.
- There is also a commented out version that creates rasters on the fly. For now we can't remove PNGs and switch to it: we need PNGs for use in manifest and Chrome Web Store. We may switch when CWS supports SVG at some point in the future.
Context: every time peer count was updated, the browser action icon got set,
which caused unnecessary  internal request for PNG assets every 3 seconds:
This change mostly makes request logs in Network tab less noisy in Brave …
> fix: avoid internal requests for action icons

- add-on/_locales/en/messages.json
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/options.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/page.js
- test/functional/lib/ipfs-request-gateway-recover.test.js
This PR closes #640, enabling dead public gateways to be redirected to the default public gateway. Added as an experimental option, defaulting to `false`.
> feat: recover from failed HTTP requests to third party gateways

- add-on/src/lib/dnslink.js
- add-on/src/lib/ipfs-request.js
- add-on/src/options/forms/experiments-form.js
- test/functional/lib/ipfs-request-gateway-recover.test.js
This PR builds on top of #783 and:
-  adds support for recovery from DNS lookup failures
-  enables recovery for all HTTP Codes >= 400 
-  recovers `.eth` DNS failures bu reopening website on EthDNS gateway at `.eth.link`
-  simplifies some code paths and adds more tests
When a third-party IPFS gateway is discontinued or censored at DNS level, the IPFS Companion should retry request using currently active gateway set by the user (public or local).
We also want to recover in situation when website with DNSLink has a valid DNS `TXT` record, but HTTP behind `A` record is down or unreachable.
*Note*: right now the only real use for DNS recovery is support .eth TLD via .eth.link gateway, however in the future this could provide means of working around DNS-based censorship (eg. by executing …
> feat: recover from DNS failures, support DNSLink for .eth

- .babelrc
- add-on/manifest.chromium.json
This PR adds an explicit [`minimum_chrome_version`](https://chrome-apps-doc2.appspot.com/extensions/manifest.html#minimum_chrome_version) to the `manifest.json` in Chromium builds.
Closes #715
> fix: set minimum_chrome_version to 72

- add-on/src/background/background.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/on-uninstalled.js
This PR displays a short feedback form  **on uninstall** of IPFS Companion browser extension.
This is a small experiment I made to get some insights about user expectations and biggest pain points. Note I have no experience in this, would appreciate honest feedback and thoughts on feasibility of such "on uninstall" feedback forms, and types of questions we should ask.
cc @ipfs-shipyard/gui, @autonome  @terichadbourne, @meiqimichelle
- when user removed IPFS Companion, the form is opened in a new tab
- we use anonymous form that does not require login
- all fields are optional
- user can provide contact information (email) if they choose to do so
- uninstall feedback form is displayed only on stable channel
- this ensures we get feedback about the official stable channel
- picked Google …
> feat: display feedback form on extension uninstall

- .babelrc
- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/runtime-checks.js
- test/functional/lib/ipfs-request-dnslink.test.js
- test/functional/lib/ipfs-request-gateway-redirect.test.js
- test/functional/lib/runtime-checks.test.js
This PR:
- changes minimal Firefox version to 68 (current [ESR](https://support.mozilla.org/en-US/kb/choosing-firefox-update-channel))
- restores CORS workaround when runtime is Firefox <69 (removed in https://github.com/ipfs-shipyard/ipfs-companion/pull/771)
This makes Companion once again compatible with Firefox ESR and Fennec-based Firefox for Android.
A way to test this is to open Firefox 68 (ESR) and go to https://audius.co using Firefox ESR and start listening to music. XHR requests sent to public gateways should get cancelled before receiving first byte of payload, and a late redirect to local gateway replaces them. (Firefox >69 redirects immediately, without the need to cancel original requet mid-flight)
Closes #784
Closes #779
CC …
> fix: restore ESR compatibility

- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
This PR disables all integrations (including protocol handlers)
when global integrations toggle is in "off" state.
It includes opening the browser action menu (it no longer triggers dnslink lookup for current tab).
Closes #821
> fix: no dnslink lookup when turned off

- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-protocol-handlers.test.js
We are unable to fix this (URI is lowercased before passed to extension), nor we are able to reconstruct the original CIDv0, but we can inform user about manual fix and link to https://cid.ipfs.io:
> ![2019-12-03--16-16-47](https://user-images.githubusercontent.com/157609/70064013-1a3d2700-15e9-11ea-85b4-9861f7461895.png)
This PR also adds SRI for CSS assets.
Closes #815, cc #527
> fix: update error page for ipfs://CIDv0 in Firefox 70+

- add-on/_locales/en/messages.json
- add-on/src/lib/context-menus.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-import.js
- add-on/src/lib/options.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/forms/file-import-form.js
- add-on/src/options/page.js
- add-on/src/popup/quick-upload.js
- test/functional/lib/ipfs-import.test.js
- test/functional/lib/quick-upload.test.js
This PR changes the upload target from `ipfs add` to MFS. Currently, it uses the default directory `ipfs-companion-uploads` with the user option to change this on the upload page. On successful upload, it will open the Web UI, at the directory used for the upload. 
closes #415 and closes #635
> feat: import files to MFS

- add-on/_locales/en/messages.json
- add-on/src/lib/context-menus.js
- add-on/src/lib/inspector.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/options.js
- add-on/src/options/forms/dnslink-form.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/page.js
- add-on/src/popup/browser-action/context-actions.js
- add-on/src/popup/browser-action/page.js
- add-on/src/popup/browser-action/store.js
- test/functional/lib/ipfs-request-dnslink.test.js
This PR changes default behavior and disables redirect of DNSLink websites
to local gateway, as noted in https://github.com/ipfs-shipyard/ipfs-companion/issues/701#issuecomment-562304730
- In the past, redirect of DNSLink websites to local gateway was enabled by default.
- User had to opt-out via redirect opt-out per hostname.
- #667 discussed problematic situation of breaking Origin of DNSLink websites.
- #701 describes agreed temporary solution 
- temporary until something like subdomain gateway on `*.localhost` (https://github.com/ipfs/go-ipfs/issues/6498) or Web Package (https://github.com/ipfs/in-web-browsers/issues/121) lets us redirect without breaking Origin isolation.
> ![2019-12-05--23-22-39](https://user-images.githubusercontent.com/157609/70279197-3b9f3e00-17b6-11ea-9dad-90f2d6 …
> feat: improved experience on DNSLink websites

- add-on/_locales/en/messages.json
- add-on/src/lib/dnslink.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/options.js
- add-on/src/options/forms/dnslink-form.js
- add-on/src/options/page.js
> For the context see #826 and discussion in https://github.com/ipfs/docs/issues/405
With https://github.com/ipfs-shipyard/ipfs-companion/pull/826 the data of visited DNSLink websites was no longer getting into the cache of local IPFS node by default.
This PR fixes the data distribution problem with a background task queue that ensures every visited DNSLink asset is preloaded to the cache of local IPFS node, contributing to the swarm. If original HTTP server is down, IPFS Companion will recover (#640) in a new tab.
This preload of DNSLink data is enabled by default, but can be disabled with a toggle on Preferences screen:
> ![2019-12-09--16-05-19](https://user-images.githubusercontent.com/157609/70446654-ba89c480-1a9d-11ea-8186-cae8468579eb.png)
> feat: preload visited DNSLink URLs to local node

- add-on/src/lib/options.js
- test/functional/lib/ipfs-request-dnslink.test.js
This PR restores DNSLink redirect to local gateway as the default setting:
https://docs.ipfs.io → http://127.0.0.1:8080/ipns/docs.ipfs.io/
During the Design Review Call for https://github.com/ipfs/docs/issues/405 we've decided to keep the default user experience of loading DNSLink websites from local gateway by default.
References:
- Meeting Notes: https://github.com/ipfs/team-mgmt/pull/1081
- Decisions: https://github.com/ipfs/docs/issues/405#issuecomment-564310469
cc https://github.com/ipfs-shipyard/ipfs-companion/pull/826 @momack2
> refactor: restore DNSLink redirect to local gateway

- add-on/_locales/en/messages.json
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-path.js
- add-on/src/lib/ipfs-proxy/enable-command.js
- add-on/src/lib/ipfs-proxy/pre-acl.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/options.js
- add-on/src/lib/state.js
- add-on/src/options/forms/gateways-form.js
- add-on/src/options/page.js
- add-on/src/popup/browser-action/context-actions.js
- add-on/src/popup/browser-action/operations.js
- add-on/src/popup/browser-action/page.js
- add-on/src/popup/browser-action/store.js
- add-on/src/popup/browser-action/tools.js
- add-on/src/popup/page-action/page.js
- test/functional/lib/ipfs-proxy/enable-command.test.js
- test/functional/lib/ipfs-proxy/pre-acl.test.js
- test/functional/lib/state.test.js
This PR replaces per-site redirect toggle with one that disables ALL IPFS integrations: redirect to local gateway, injection of content scripts, DOM changes, and access to API via [window.ipfs](https://github.com/ipfs-shipyard/ipfs-companion/blob/master/docs/window.ipfs.md)
closes  #828, closes #820, cc #710, #689, #589 
Instead of disabling redirect per website, users should be able to disable all  integrations that change page, mutate DOM etc.
(`noRedirectHostnames` → `noIntegrationsHostnames`)
User can disable IPFS per host, including DNSLink websites:
> ![2-2019-12-11--16-45-47](https://user-images.githubusercontent.com/157609/70636742-52bab180-1c36-11ea-8d90-cab67a42f017.png)
If website is powered by DNSLink, the toggle will disable redirect, but there will be an option to open it …
> feat: disable integrations per website

- add-on/src/lib/copier.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-import.js
- add-on/src/popup/quick-import.js
> @ericronne suggested that best interface is no interface, so..
This PR adds automatic copying of shareable link to clipboard when user imports a file via IPFS Companion UI. Closes #833.
Import file via context menu or "Share files via IPFS" from the main menu.
A system notification in system-native look will be shown at the same time imported file is being opened in Web UI:
> ![2019-12-12--13-32-56](https://user-images.githubusercontent.com/157609/70712384-f4e4a300-1ce3-11ea-9761-195d267a8cd3.png)
This notification is the same as one when user manually copies via:
> ![2019-12-12--13-34-46](https://user-images.githubusercontent.com/157609/70712502-35442100-1ce4-11ea-8ea9-dd8e9a0fb55b.png)
> feat: copy shareable link during file import

- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-protocol-handlers.test.js
> fix: ipfs:// in Firefox incognito window

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-workarounds.test.js
This PR fixes broken DNSLink loads for `/ipns/ipfs.io/blog/*` from local or public gateways.
Without this, user stumbling upon https://ipfs.io/blog/2020-02-10-our-focus-for-2020/ will get redirected to  http://127.0.0.1:8080/ipns/ipfs.io/blog/2020-02-10-our-focus-for-2020/ and get HTTP 404 error without any indication how to fix it, which is pretty bad experience:
```console
ipfs resolve -r /ipns/ipfs.io/blog/2020-02-10-our-focus-for-2020/: no link named "2020-02-10-our-focus-for-2020" under bafybeics2j3x4qcn3365docj4f5xfe7gwlbakds7x3it63okc572imyb4e
```
Wider context: https://github.com/ipfs/blog/issues/360
cc @autonome  (as I am not sure who is responsible for ipfs.io atm)
> fix: broken dnslink at /ipns/ipfs.io/blog/foo

- add-on/manifest.common.json
This PR is addressing Chrome Web Store review (https://github.com/ipfs-shipyard/ipfs-companion/issues/808#issuecomment-590313139)
We no longer use `alarms` API (Chrome behaved differently than Firefox)
and `activeTab` is superseded by  `<all_urls>` (old Firefox bug is no longer a problem).
> fix: remove redundant/unused permissions

- add-on/_locales/en/messages.json
Closes #857
- `Copy Public Gateway URL` → `Copy shareable link`
- `Copy IPFS Path` → `Copy IPFS content path`
> ![2020-04-05--15-05-58](https://user-images.githubusercontent.com/157609/78499101-fcc2ca00-774e-11ea-9a28-82ab5ad490bd.png)
> style: rename menu items for copying and sharing

- add-on/manifest.chromium.json
- add-on/manifest.common.json
- add-on/src/contentScripts/ipfs-proxy/page.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/options/forms/experiments-form.js
- docs/window.ipfs.md
> parent #589 
- Mitigates #856
- Mitigates #852
> fix: disable window.ipfs until JS API is updated

- add-on/src/lib/ipfs-path.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/options.js
- test/functional/lib/ipfs-path.test.js
- test/functional/lib/ipfs-request-gateway-redirect.test.js
This normalizes `http://0.0.0.0:5001/webui/` to `http://127.0.0.1:5001/webui/` 
Closes #867
> fix: normalize API calls from 0.0.0.0 to 127.0.0.1

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-gateway-recover.test.js
> Fixes #873 
The changes caused some tests to fail, and I'm not sure my javascript skills are good enough to figure out how to fix them properly without just deleting them.
```
419 passing (2s)
1 pending
7 failing
1) requestHandler.onCompleted:
with recoverFailedHttpRequests=true
should redirect to default subdomain gateway on broken subdomain gateway request:
AssertionError: tabs.create should be called with default subdomain gateway URL: expected false to be truthy
at Context.<anonymous> (test/functional/lib/ipfs-request-gateway-recover.test.js:57:14)
2) requestHandler.onCompleted:
with recoverFailedHttpRequests=true
should recover from unreachable third party public gateway by reopening on the public gateway:
AssertionError: tabs.create should be called with IPFS default public …
```
> fix: HTTP recovery in the same tab

- add-on/manifest.common.json
- package.json
- webpack.config.js
Turns out `web-ext` ignores everything under `node_modules` no matter how deep in the project tree it is:
https://github.com/mozilla/web-ext/blob/065188db35a4f63c2d17ff744cc1de2601a62222/src/util/file-filter.js#L40-L46
That caused `/dist/bundles/node_modules/ipfs-css/fonts` to be excluded from the production package :-(
The fix here is to put all assets under hardcoded `/dist/bundles/assets/` which is not excluded.
cc @jessicaschilling – ignore if fonts look weird, this will fix them
> fix: include CSS assets in the install package

- add-on/src/lib/http-proxy.js
- add-on/src/options/forms/dnslink-form.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/forms/file-import-form.js
- add-on/src/options/forms/gateways-form.js
- add-on/src/options/forms/ipfs-node-form.js
- docs/README.md
- docs/dnslink.md
- docs/node-types.md
- docs/window.ipfs.md
- docs/x-ipfs-path-header.md
The legacy IPFS Docs site has been deprecated, so links to `docs-beta.ipfs.io` will auto-redirect to `docs.ipfs.io`. This PR doesn't change much from the user's perspective, but it makes things a bit tidier.
> chore: update docs links to non-beta site

- DEVELOPER-NOTES.md
This PR adds docs on `npm run watch` (Run build on file changes)
(dannycarrera on IRC was looking for functionality provided by `watch`,  but it was missing from `DEVELOPER-NOTES.md`)
> docs: npm run watch

- add-on/_locales/en/messages.json
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/options.js
- add-on/src/lib/state.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/page.js
This adds an opt-in for loading webui from DNSLink at https://webui.ipfs.io, which includes bleeding edge version built from ipfs-webui master branch.
The opt-in toggle on Preferences looks like this:
> ![2020-06-08--23-09-00](https://user-images.githubusercontent.com/157609/84081338-10eca700-a9de-11ea-8890-abbcc6352a68.png)
Closes #860
> feat: option to opt-in for bleeding edge ipfs-webui

- add-on/_locales/en/messages.json
- add-on/_locales/fi/messages.json
- add-on/_locales/hu/messages.json
- add-on/_locales/ko_KR/messages.json
- add-on/_locales/ru/messages.json
- add-on/_locales/tr/messages.json
- add-on/_locales/zh_TW/messages.json
This PR changes `manifest_extensionDescription` in order to update taglines in Chrome and Firefox extension stores.
Old: "Browser extension that simplifies access to IPFS resources"
New: "Harness the power of IPFS in your browser"
Ref https://github.com/ipfs-shipyard/ipfs-companion/issues/896
> style: update manifest_extensionDescription

- PRIVACY-POLICY.md
This PR adds section on DNSLink lookup  to the Privacy Policy document.
For context, see #900 
cc @Snawoot
> docs: add DNSLink lookup to Privacy Policy

- add-on/_locales/ar/messages.json
- add-on/_locales/ca/messages.json
- add-on/_locales/cs/messages.json
- add-on/_locales/da/messages.json
- add-on/_locales/de/messages.json
- add-on/_locales/en/messages.json
- add-on/_locales/es/messages.json
- add-on/_locales/fi/messages.json
- add-on/_locales/fr/messages.json
- add-on/_locales/hu/messages.json
- add-on/_locales/id/messages.json
- add-on/_locales/it/messages.json
- add-on/_locales/ja_JP/messages.json
- add-on/_locales/ko_KR/messages.json
- add-on/_locales/nl/messages.json
- add-on/_locales/no/messages.json
- add-on/_locales/pl/messages.json
- add-on/_locales/pt/messages.json
- add-on/_locales/pt_BR/messages.json
- add-on/_locales/ro/messages.json
- add-on/_locales/ru/messages.json
- add-on/_locales/sv/messages.json
- add-on/_locales/tr/messages.json
- add-on/_locales/zh_CN/messages.json
- add-on/_locales/zh_TW/messages.json
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/forms/reset-form.js
- add-on/src/options/options.css
- add-on/src/options/page.js
Assorted fixes to the prefs page:
- The big reset button is now in its own section (instead of under Experiments)
- Updated "open in new window" icon for "read more" links to match the ones for pinning services UI added to ipfs-css: see https://github.com/ipfs-shipyard/ipfs-css/pull/43
- Tweaks language throughout prefs page for clarity
> style: Preferences page tweaks

- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-protocol-handlers.test.js
This PR search/replaces globally: bafkreiewrj2pugsghd3flw2lk2fhvtmz6wipecnxep5qc5m3lfpf2mvjk4 -> QmVGC4uCBDVEhCzsaJmvR5nVDgChM97kcYNehVm7L9jxtc
https://gateway.ipfs.io/ipfs/QmVGC4uCBDVEhCzsaJmvR5nVDgChM97kcYNehVm7L9jxtc is an improved "Cannot process IPFS request" page with better information hierarchy and clearer guidance for next steps. 
Local screenshots with fake URIs bashed in for the sake of illustration:
Closes https://github.com/ipfs-shipyard/ipfs-companion/issues/815
> docs: improved "Cannot process IPFS request" page

- add-on/_locales/en/messages.json
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/on-installed.js
- add-on/src/lib/options.js
- add-on/src/options/forms/experiments-form.js
- add-on/src/options/page.js
This PR adds functionality for displaying the GitHub page for latest version release notes (taken from `browser.runtime.getManifest().version` in order to be accurate for Beta channel users) upon version update of the extension.
Closes https://github.com/ipfs-shipyard/ipfs-companion/issues/912
> Display channel-appropriate release notes upon Companion version update

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-gateway-recover.test.js
- test/functional/lib/ipfs-request-workarounds.test.js
> fix: regression in HTTP recovery of background tabs

- add-on/_locales/en/messages.json
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-request.js
- add-on/src/lib/options.js
- add-on/src/lib/state.js
- add-on/src/options/forms/dnslink-form.js
- add-on/src/options/forms/gateways-form.js
- add-on/src/options/forms/ipfs-node-form.js
- add-on/src/options/page.js
- add-on/src/popup/browser-action/store.js
- package.json
- test/functional/lib/ipfs-proxy/enable-command.test.js
- test/functional/lib/ipfs-proxy/pre-acl.test.js
- test/functional/lib/state.test.js
This PR improves the way we handle manual opt-out performed per site by the user by storing both opt-out and opt-in decisions made by the user.
- _Preferences_ screen now has separate list for opt-outs and opt-ins:
> ![2020-10-15--04-48-21](https://user-images.githubusercontent.com/157609/96071073-b25e9a80-0ea1-11eb-986d-5fde11581774.png)
- In the past we only had opt-out list named `noIntegrationsHostnames`. 
- Items from the old list are automatically migrated to the new one named `disabledOn`.
- If for some reason item is present on both lists, opt-out takes a priority.
- The above lists can be modified by hand on _Preferences_ screen, 
however the expectation is that most of the time users will not touch them. 
- Instead, user will be toggling integrations for current website via …
> feat: remember manual opt-ins and opt-outs per site

- DEVELOPER-NOTES.md
- README.md
Updates `README.md` and `DEVELOPER_NOTES.md` to the following:
- Advises using `npm run dev-build` rather than `npm install`
- Calls out `npm run dev-build chromium` and `npm run dev-build firefox:nightly` as all-in-one shortcuts
- Updates outdated instructions for manual loading extension in FF and Chromium (and removes old animated gifs as they're outdated and redundant; can update to new gifs if we feel it's necessary)
> docs: updated developer notes

- add-on/_locales/en/messages.json
- add-on/src/lib/context-menus.js
- add-on/src/lib/copier.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-path.js
- add-on/src/popup/browser-action/browser-action.css
- add-on/src/popup/browser-action/context-actions.js
- add-on/src/popup/browser-action/gateway-status.js
- add-on/src/popup/browser-action/header.js
- add-on/src/popup/browser-action/nav-header.js
- add-on/src/popup/browser-action/page.js
- add-on/src/popup/browser-action/store.js
- add-on/src/popup/browser-action/tools-button.js
- add-on/src/popup/browser-action/tools.js
- package.json
Closes https://github.com/ipfs-shipyard/ipfs-companion/issues/740.
This PR moves @deedlefake's work originally in https://github.com/ipfs-shipyard/ipfs-companion/pull/745 to account for some significant changes to the codebase since then.
Local page
🚨 🚨 **Ordinary web2 page (this ain't right!):**
Gateway page:
DNSLink page:
> feat: snapshot link and IPNS path copy options

- add-on/src/lib/ipfs-client/external.js
This removes unnecessary normalization of ipv6 URLs and partially unblocks (#904)
Real fix needs to land in go-ipfs (https://github.com/ipfs/go-ipfs/pull/7731)
> fix: support API on ipv6 with go-ipfs 0.8+

- add-on/src/lib/options.js
- add-on/src/lib/state.js
- package.json
- test/functional/lib/options.test.js
- yarn.lock
> fix: IP support on opt-in and opt-out lists

- add-on/src/lib/options.js
- test/functional/lib/options.test.js
Previous version of the function was reporting addresses like ``]::1[`` or even ``]:]:]1]`` as valid.
> fix: isHostname reports malformed IPv6 addresses as valid

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-workarounds.test.js
This PR fixes Companion in Firefox 85 (and 86 Nightly) and closes #955
Based on my debugging session with Firefox Nightly stopped leaking unique extension ID via Origin header. Probably to reduce the surface for fingerprinting, which is pretty funny considering that around v72 Chromium moved... in the opposite direction: Chromium was sending anonymous `Origin: null` and now v86 sends extension ID instead  :man_shrugging: 
Overall, the behavior of  `Origin` HTTP header in XHRs coming from within browser extension is not reliable: vendors change this behavior back and forth, often contradicting each other.
Refactored the way we detect requests coming from the Companion extension to be independent of the brittle Origin HTTP header – instead, we now inspect requests via lower level …
> fix: external node in Firefox 85+

- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-protocol-handlers.test.js
Some improvements to the intermediate router page we use for URI support:
:point_right: Open "Test" links in incognito window, it will use public gateway as a fallback and give better feeling of how things behave when network is slow.
- Demo: https://bafkreiacamq42cltx3ussmxb2ey3mmpisthrs3kelwuxnwt7oofvqsjvgm.ipfs.dweb.link/#ipfs%3A%2F%2FQmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco%2Fwiki%2FDiego_Maradona.html
- This can ship before we land https://github.com/ipfs/in-web-browsers/issues/169 – we will update our GW when go-ipfs 0.8.0 ships
- Test: https://bafkreiacamq42cltx3ussmxb2ey3mmpisthrs3kelwuxnwt7oofvqsjvgm.ipfs.dweb.link/#ipns%3A%2F%2Fdocs.ipfs.io
- this removes the need for bumping library version when new encoding/codec is added, making this more future proof
- we still check …
> fix: URI router preserving the URI path

- add-on/src/lib/ipfs-path.js
- add-on/src/lib/ipfs-request.js
- test/functional/lib/dnslink.test.js
- test/functional/lib/ipfs-path.test.js
- test/functional/lib/ipfs-request-workarounds.test.js
This is a cosmetic fix that ensures IPFS resources are redirected to
`ipfs://` or `ipns://` URI and that URI is displayed in the browser UI
in the address bar.
Due to the way Brave implemented URI cloak for local HTTP-based gateway
provided by go-ipfs managed by the browser itself the regular redirect
done via webRequest API did not produce native URI in address bar.
However, `tabs.update` does the trick, so we use that for root requests.
We can remove this in the future, if webRequest behavior is fixed.
cc @autonome (mitigates issue we both discovered independently)
> fix: redirect to native URI in Brave

- add-on/src/lib/dnslink.js
This fixes #877. I couldn't add any tests because, from what i saw, readDnslinkFromTxtRecord always get mocked. If this is a problem, and someone can point me to the right direction I could add tests.
> Change DNS resolution endpoint to allow ipns recursive resolution

- add-on/src/lib/ipfs-path.js
- add-on/src/popup/browser-action/context-actions.js
- add-on/src/popup/browser-action/store.js
- package.json
- test/functional/lib/dnslink.test.js
- test/functional/lib/ipfs-path.test.js
- yarn.lock
Final batch of fast-tracked cosmetics: 
- support for automatic redirect of inlined DNSLink names on subdomain gateways (https://github.com/ipfs/in-web-browsers/issues/169)
- restore context actions for pages loaded via native URIs (when `ipfs://`, `ipns://` is in address bar in Brave)
(in the past two years we've added subdomains and now native URIs: need to clean up and refactor most of ipfs-path, but that will be done in separate PRs as part of #939)
> fix: inlined DNSLink names and context actions for URIs

- add-on/src/lib/ipfs-client/index.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/on-installed.js
This PR improves onboarding experience  on Brave.
* Before this PR, user had to manually swith node type to "Provided by Brave"
* With this PR, when IPFS Companion is installed for the first time in Brave
* AND there is no IPFS Daemon on port 8080 (defult go-ipfs and IPFS Desktop)
* IF Brave node is already running, Companion will use it 
* IF Brave node is not running, Companion will trigger onboarding flow
- This is a small change that will default to endpoint provided by Brave when Brave runtime is detected and if the current endpoint (by default 127.0.0.1:8080) is offline.
- This means user won't need to go to preferences and switch the backend to "Provided by Brave"
- new users will have that set for them automatically 
- (more or less what @Gozala suggested during this week's …
> feat: switch to brave node if the default port is offline

- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-workarounds.test.js
This PR disables redirect for requests that would fail due to Brave Shields rules.
Closes #962
> fix: interop with Brave Shields rules

- DEVELOPER-NOTES.md
- README.md
- add-on/src/lib/ipfs-companion.js
- add-on/src/popup/browser-action/browser-action.css
- add-on/src/popup/browser-action/header.js
- add-on/src/popup/browser-action/icon.js
- add-on/src/popup/browser-action/store.js
- add-on/src/popup/browser-action/version-update-icon.js
Closes #964 
> ![Peek 2021-01-30 03-03](https://user-images.githubusercontent.com/157609/106344162-5f222380-62a9-11eb-843d-5b57fcf1430d.gif)
> chore: remove beta channel

- add-on/src/landing-pages/welcome/page.js
- add-on/src/lib/constants.js
- add-on/src/lib/ipfs-client/brave.js
- add-on/src/lib/ipfs-companion.js
- add-on/src/lib/ipfs-path.js
- add-on/src/lib/on-installed.js
- add-on/src/popup/browser-action/store.js
- test/functional/lib/ipfs-path.test.js
This PR closes #982
- remove custom HTML UI (Brave 1.23.22+ provides own UI)
- use bafkqaaa as the trigger
- cleanup bafkqaaa, switch to Preferences/Welcome page
- single codebase, works in both old and new Brave
> refactor: adjust Brave activation UI flow

- add-on/manifest.firefox.json
- add-on/src/lib/ipfs-request.js
- test/functional/lib/ipfs-request-protocol-handlers.test.js
This replaces JS-based router with URI router introduced in https://github.com/ipfs/go-ipfs/pull/7802
Every gateway running go-ipfs 0.8.0 or later has this now.
It not only removes the need for JS-based router, but makes it future-proof, as gateway takes care of redirects to subdomains and/or  base conversion, if needed.
> chore: native uri router

- add-on/src/lib/ipfs-client/brave.js
- test/functional/lib/ipfs-request-workarounds.test.js
- yarn.lock
This replaces `bafkqaaa` with `bafkqae2xmvwgg33nmuqhi3zajfiemuzahiwss` to ensure gateway response in go-ipfs 0.9 does not error (+  provide human-readable response in case someone copies it from address bar)
Fixes https://github.com/brave/brave-browser/issues/16671
> fix: onboarding flow in Brave

- CONTRIBUTING.md
current contributing.md link returns 404.
This link is also broken in some other projects of this organization. All instances can be checked using https://github.com/search?q=org%3Aipfs+%22community%2Fblob%2Fmaster%2Fcontributing.md%22&type=Code&ref=advsearch&l=&l=
Unfortunately github doesn't offer case-sensitive search so we can't filter exact number of instances.
> docs: fix community CONTRIBUTING.md links

- CONTRIBUTING.md
- test/data/linkify-demo.html
- test/functional/lib/dnslink.test.js
- test/functional/lib/ipfs-request-gateway-redirect.test.js
> fix: linkify tests

- .github/workflows/ci.yml
Looks like builds are broken on `windows-latest`: https://github.com/ipfs/ipfs-companion/actions/workflows/ci.yml
The reported error: `gyp ERR! stack Error: Could not find any Visual Studio installation to use`
I could not test this as I don't have perms to run CI nor do I have access to a windows machine atm, but there seems like two ways to fix this:
- We can either move to node-v16 which ships with build tools.
- Or add this dependency based on https://github.com/felixrieseberg/windows-build-tools
the github `actions/setup-node@v1` is also 2 major versions behind, so should be upgraded as well, but I'm unsure of the breaking API changes between the two.
🤞🏽 this should fix the broken builds in theory.
> fix(ci): windows build

- .editorconfig
- add-on/src/lib/ipfs-client/index.js
- add-on/src/lib/ipfs-client/reloaders/index.js
- add-on/src/lib/ipfs-client/reloaders/internalTabReloader.js
- add-on/src/lib/ipfs-client/reloaders/localGatewayReloader.js
- add-on/src/lib/ipfs-client/reloaders/reloaderBase.js
- add-on/src/lib/ipfs-client/reloaders/webUiReloader.js
- add-on/src/lib/ipfs-companion.js
- package.json
- test/functional/lib/ipfs-client/reloaders/reloaders.test.js
- yarn.lock
Closes https://github.com/ipfs/ipfs-companion/issues/1010
In this PR:
- I added support for reloading failed tabs when API is available again, by:
- By statically checking for failed tabs which belongs to local gateway instead of tracking all URLs.
- This reduces the complexity for tracking failed websites in `content_scripts`.
- More details on the implementation can be found in the relevant reloader.
- I am also introducing a plugin mechanism that can register different reloader classes, this provides decent segregation of validation logic and also allows us to have reusable code for reloading.
- Added relevant unit tests for 100% coverage.
- Also updated the `yarn.lock` file and added a matching `.editorconfig` to configure IDEs.
Screencast: …
> feat: reload failed IPFS tabs when API becomes available

- add-on/src/lib/ipfs-companion.js
#1017 
**About**
The issue opener found out that when number of peers is 1000 or above, the last digit might be partially invisible and cause confusion due to the badge's max width. 
The core team replied to the issue suggesting to truncate it in the format of "1k", "2k". So I implemented the approach and made this PR.
**Original UI**
**Committed UI Change**
Show full number when < 999
This is my first PR, please let me know if I could do it better, looking forward to help with other tasks of this repo and IPFS!
> fix: truncate no. of peers to unit of "k" when > 999

- add-on/src/popup/quick-import.js
#1028 
**About** 
When a user specified a custom path to store imported file while importing with the quick import popup, the path will be saved to preference and will be automatically applied next time.
**Remarks**
The issue opener suggests to save path to preference as long as the textbox lost focus.
I have concern that, sometimes the path might be incomplete / not valid when user lost focus of the textbox.
So for the code I commit, I save the path to preference after a successful import to make sure the path is completed already and is valid
Please let me know if you would like me to do any other approaches.
> feat: save "Path to store imported files" preference from import page

- .github/workflows/ci.yml
- package-lock.json
- package.json
`npm test`  takes ~30s. If it hangs for longer than a minute, it is clearly a bug.
This PR  ensures we get failure sooner than after 360m (default on github)
CI hang problem appeared around #1101 –  i think it is c8   being very, very slow  – note that tests finish correctly, but node process hangs and never exists.
> fix(ci): hanging tests

- package.json
This PR fixes mocha hangs.
Without this, tests sometimes hang due to racy tests or missing orchestration cleanup.
`npm test` should finish <3s, then c8 takes a few additional seconds, but  sometimes it hangs forever and leads to timeout:
- https://github.com/ipfs/ipfs-companion/actions/runs/3541084119/jobs/5944912207#step:11:529
> fix(test): exit mocha

- PRIVACY-POLICY.md
Update the Privacy Policy to use 2023-01-24 Privacy Policy written by our legal team
see https://docs.google.com/document/d/1rlUxx1Yy7bPqKE_LQ42vqaYSd0xdPsZQSKmkcjMT76U
> chore: update PRIVACY-POLICY.md

- add-on/src/lib/redirect-handler/blockOrObserve.ts
Closes: #1274 
Broken in: #1266
Cause: MV3 APIs accessed in MV2 Scope
Test:
- there is no easy/automated way to test this, I spent some time looking into writing an e2e test, but nope.
> fix(mv3): FF Browser Action

- docker-compose.e2e.yml
- test/e2e/ipfs-companion.test.js
Related to: #1300 
In this PR:
- ❌ Firefox E2E are disabled.
- ✅ Chromium E2E should work.
- root-cause: https://github.com/w3c/webextensions/issues/227 `host_permissions` cannot be granted, yet!
More in comments.
> fix(test): 🚧 Making e2e Tests work again.

- add-on/src/lib/precache.js
This PR aims to fix webui preload in Kubo 0.24.
Context: `ipfs.dns` has been deprecated for a while, and the way we use it here got broken in Kubo 0.24: https://github.com/ipfs/kubo/pull/10212
> fix: ipfs.dns → ipfs.resolve

- .github/workflows/ci.yml
v3 is no longer supported as per https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
> chore: update upload-artifact action to v4

- .github/workflows/ci.yml
This PR updates the deprecated version of actions/cache (v3.2.4) to the latest version (v4) to resolve CI failures in https://github.com/ipfs/ipfs-companion/pull/1328
The error message that prompted this change was:
> Error: This request has been automatically failed because it uses a deprecated version of . Please update your workflow to use v3/v4 of actions/cache to avoid interruptions. Learn more: https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
> 
> \- https://github.com/ipfs/ipfs-companion/actions/runs/13635460809/job/38113001518?pr=1328
> chore: update actions/cache from v3.2.4 to v4

- add-on/src/lib/dnslink.js
- prevent privacy DNS leak by not sending requests to external services
- removed hardcoded fallback to https://ipfs.io/ when offline
- return `undefined` when offline to avoid caching false negatives
- closes https://github.com/ipfs/ipfs-companion/issues/1337
- added in-flight request tracking with pendingLookups Map
- prevents multiple simultaneous API calls for the same FQDN
- reduces redundant requests from 2-4 down to 1 per domain
> fix: skip DNSLink resolution when offline, deduplicate inflights
