lib/gateways.js
lib/gui.js

Continuation of  #29 in a new branch. This one uses the notifications api, and should be safe to merge after some testing. I think gui improvements should be in a separate pull request/issue...

Add pin function

---

package.json

chore(package): update sinon-chrome to version 2.2.1

---

add-on/manifest.json
add-on/src/options/options.html

Fix preferences screen in Firefox 55

---

README.md
add-on/manifest.json

Add Chrome Web Store link and update AMO  one

---

add-on/manifest.json
package.json

Remove unsafe-eval from CSP whitelist

---

add-on/manifest.json
add-on/src/options/options.html
add-on/src/popup/browser-action.html
add-on/src/popup/quick-upload.html

This PR introduces nice user experience on Firefox for Android and closes #109

CSS fixes for Android

---

add-on/src/popup/browser-action/store.js

- closes #338
- as a side-effect this PR may improve situation with #318 
- I tested in Chrome under Linux and popup never breaks
- would be great if someone checked under macOS, as we suspect it to be platform-specific
- it should not break anything under Brave, but l'd sleep better if someone confirmed it works there too – would appreciate a quick smoke-test :-)

Browser Action popup fixes

---

Dockerfile
README.md
ci/Jenkinsfile
package.json
test/functional/lib/ipfs-companion.test.js

This PR aims to add stable Jenkins-based CI setup + reproducible build.
When done, closes #364

Add Jenkinsfile with docker-based build

---

package.json
yarn.lock

With fixes for buffer serialization in pubsub subscription handler functions

Upgrades to ipfs-postmsg-proxy@2.8.3

---

package.json

Removes surprising --fix arg to standard

---

docs/examples/window.ipfs-fallback.html
docs/window.ipfs.md

In the interests of enabling developers...

Adds an example for fallback when window.ipfs is unavailable

---

CONTRIBUTING.md
README.md
docs/brave.md
docs/developer-notes.md
docs/firefox-for-android.md
docs/window.ipfs.md

- extracts `docs/developer-notes.md` from `CONTRIBUTING.md`
- extracts `docs/firefox-for-android.md` from `docs/developer-notes.md`
- extracts `docs/brave.md` from `README.md`
- general cleanup, fixed broken cross-repo links
- fix: link to window.ipfs fallback demo (#411)

Docs reorganization 

---

README.md

Updated main GIF and Features list:
- [PREVIEW](https://github.com/ipfs-shipyard/ipfs-companion/blob/2ecbaab5d8e54065979df59e1f803f7bc73bc183/README.md)
Would be super cool if someone looked at copy and suggested improvements (if something sounds weird or id unclear).

README updates for v2.2.0

---

docs/window.ipfs.md

→ [PREVIEW](https://github.com/ipfs-shipyard/ipfs-companion/blob/6c4b2463b0ad70debc5b240d770c30082b9056f1/docs/window.ipfs.md)
It sets proper expectations + encourages people to provide feedback in github issues.

Add Disclaimer at the top of window.ipfs.md

---

add-on/src/popup/browser-action/operations.js
add-on/src/popup/browser-action/store.js
package.json
yarn.lock

Details in https://github.com/ipfs/js-ipfs-api/pull/764

fix: ipfs.util.addFromURL with URL-escaped file names

---

add-on/_locales/it/messages.json
add-on/_locales/sv/messages.json
add-on/manifest.common.json

Fix delivered to Beta in #494 looks stable enough to be promoted to Stable
This PR:
- synchronizes locales with [crowdin](https://crowdin.com/project/ipfs-companion)
- bumps version in preparation to stable release

release chores: version bump and locale sync

---

add-on/src/contentScripts/linkifyDOM.js

Linkify is an opt-in experiment on _Preferences_ screen:
A lot of web-based text editors create elaborate DOM trees and together with @lgierth  we've experienced it first hand that  it is not enough to check if parent is safe for linkification. 
This change walks back over entire parent tree to ensure none of parents
has a no-go flag for linkification (eg. HTMLElement.contentEditable property)
Test pages:
- https://ipfs.io/ipfs/bafybeidvtwx54qr44kidymvhfzefzxhgkieigwth6oswk75zhlzjdmunoy/linkify-demo.html
- https://hackmd.io/kMlFFc_bQoiabAul5RjYag?both#
- Left pane (editor) will be ignored after this PR is merged. Right now, if multiple people edit the same line, content gets destroyed.

Linkify fix to run safety checks on entire parent tree

---

add-on/src/popup/quick-upload.css

Fixes https://github.com/ipfs-shipyard/ipfs-companion/issues/559.

fix: update share checkbox arrows

---

package.json
yarn.lock

Switch to latest webextension-polyfill

---

add-on/_locales/en/messages.json
add-on/src/lib/context-menus.js
add-on/src/lib/ipfs-companion.js

This PR implements and closes #569, which is a simple, but powerful idea:
Selected text can be added to IPFS with one click :ok_hand:  
Super handy for quickly sharing snippets or quotes:

Feature: Add selected text to IPFS

---

add-on/_locales/cs/messages.json
add-on/_locales/da/messages.json
add-on/_locales/de/messages.json
add-on/_locales/es/messages.json
add-on/_locales/fr/messages.json
add-on/_locales/it/messages.json
add-on/_locales/nl/messages.json
add-on/_locales/no/messages.json
add-on/_locales/pt/messages.json
add-on/_locales/sv/messages.json
add-on/_locales/zh_CN/messages.json

:muscle:  :globe_with_meridians: :writing_hand: 
- Contributions from https://www.transifex.com/ipfs/ipfs-companion/
- Updates: cs, de, es, fr, it, pl, pt, sv, zh-CN
- New locales: da, nl and no (thanks!)

feat: locale sync

---

package.json

- [v2.1.1](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.1.1) 
- key changes happened in [v2.1.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.1.0)

ipfs-webui v2.1.1

---

package.json

See: https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.2.0
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

feat: Update Web UI to v2.2.0

---

README.md

don't bury the lede! INSTALL NOW! Copies the add on store bages to the top, simplifies away the chromium bit, and upgrades the tag line!
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

docs: show install links at the top of the README

---

Dockerfile
ci/Jenkinsfile

- [v10.13.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.13.0)

chore: switch to latest Node LTS

---

package.json

Check [release v2.3.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.0) to see the latest changes.

feat: update to Web UI v2.3.0

---

package.json

Check [release v2.3.2](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.2) to see latest changes.

feat: update to Web UI v2.3.2

---

package.json

This fixes a regression for adding files/folders introduced in the previous release.
Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.3.3) for more info.

chore: update to Web UI v2.3.3

---

add-on/src/lib/state.js

Analytics are now **opt-in**. Check the [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.1)!

chore: update to Web UI v2.4.1

---

add-on/src/lib/state.js

This fixes a bug that prevented the adding of files 😬 - [release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.4.4).

chore: update to Web UI 2.4.4

---

add-on/_locales/pt_BR/messages.json

> Part of https://github.com/ipfs/i18n/issues/7
This PR adds Brazilian translation contributed by @agentofuser (Thank you!)

feat(i18n): add pt_BR locale

---

add-on/manifest.common.json

Firefox added support for unlimited storage some time ago, let's request it for future use in embedded node.
Closes #703, empowers embedded gateway from #664

feat: unlimited storage for embedded js-ipfs

---

add-on/src/lib/state.js

Release notes of [v2.5.0](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.0).

chore: update to Web UI 2.5.0

---

add-on/src/lib/state.js

See https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.1.

feat: web ui 2.5.1

---

add-on/src/lib/state.js

https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.5.2

feat: web ui 2.5.2

---

add-on/src/lib/state.js

[Release notes](https://github.com/ipfs-shipyard/ipfs-webui/releases/tag/v2.7.1).

feat: web ui 2.7.1

---

add-on/src/lib/context-menus.js

https://github.com/ipfs-shipyard/ipfs-companion/issues/861
code by @lidel

fix: import to ipfs is disabled

---

README.md

Update Companion readme screenshots and gifs for new UI.
@lidel -- could you please merge this when you submit to the add-on stores? Thanks 😊

docs(README): update screenshots for new UI

---

README.md

Update readme screenshots to account for UI updates in 2.16.0.

chore: update screenshots

---

README.md

Signed-off-by: Luís Ferreira <contact@lsferreira.net>

readme: fix TOC for Privacy & license info section

---

package-lock.json
package.json
webpack.config.js

fix: toggle buttons on Firefox

---

add-on/manifest.common.json

chore: v2.20.0 update

---

docs/RELEASE-PROCESS.md

update chrome web store publishing details

chore: update RELEASE-PROCESS.md
